services:
  - type: web
    name: futebol-backend
    env: python
    plan: free
    region: oregon

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120

    envVars:
      API_FOOTBALL_KEY:
        value: "0ef953667b0b3637e0d99c6444bfcb10"
      PYTHON_VERSION:
        value: "3.11"

    autoDeploy: true


